- hosts: localhost
  become: yes
  - name: Installing packages
    dnf:
      name: "{{ item }}"
      state: installed
    with_items:
      - vim
      - git
      - gnome-tweak-tool
      - vlc
      - yum-plugin-fastestmirror

  - name: clone vimrc
    git:
      repo: git@github.com:siddharthvipul/Others-stuffs.git
      dest: /tmp/

  - name: Copy the vimrc file to home directory
    copy:
      src: /tmp/Others-stuffs/vimrc
      dest: "{{ ansible_env.HOME }}/.vimrc"

  - name: Create the .vim directory in home
    command: mkdir -p "{{ ansible_env.HOME }}/.vim/bundle"
    tags:
      - vim
      - vundle

  - name: Install Vundle ( the VIM package manager )
    git:
      repo: https://github.com/gmarik/Vundle.vim.git
      dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"

  - name: Install the Vundle Plugins
    command: vim +PluginInstall +qall

